spring.data.mongodb.uri=mongodb+srv://davilopesamorim56:LtOWFJFVnMpbshdH@pauta.2gdia.mongodb.net/?retryWrites=true&w=majority&appName=Pauta
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
spring.data.mongodb.database=db