# ... Deployment YAML definition
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pauta-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pauta-api
  template:
    metadata:
      labels:
        app: pauta-api
    spec:
      containers:
        - name: app
          image: davilopess/pauta-api:1.0.2
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-uri-secret
                  key: MONGO_URI 
          imagePullPolicy: Always


